### ISSUE TITLE
Admin cadastra promoção no sistema

### ISSUE THREAD

**Issue by HenriqueMorato** [TreinaDev/esperto-fit-promocoes#8]
Eu, admin do sistema, posso cadastrar promoções. O cadastro deve conter:

- Nome da promoção
- Descrição
- Código alfanumérico único
- Percentual de desconto
- Número máximo de usos dos cupons
- Período de validade

**Comment by Alexandre-Luiz** [comment]
Coloquei uma descrição na issue que o Henrique criou. Vejam se ficou faltando alguma informação.
